### ISSUE TITLE
Error setting PWM frequency to xxx -> ignore?

### ISSUE THREAD

**Issue by jn128c** [vertueux/i2c_pwm_board#1]
Thanks for building this package.
I´m able to run the launch file but can´t pub topics or anythin else.  There is no subscriber to it. 
Im not sure using the correct prompt for the messages. Can you give some more description to it?
BR

**Comment by jn128c** [comment]
Ok, i can move one servo now by using the ServoArray message :-) will figure out the rest. 
BTW Using Nvidia Jetson NX with Docker and Ros2 Humble

**Comment by vertueux** [comment]
Hi, 
First, I would like to thank you for taking a look at my repository for your project 🙃.  

Since this project is an adaptation for ROS2 of another one, I would recommend you to take a look at [the old documentation](https://gitlab.com/fmrico/ros-i2cpwmboard/-/tree/master/doc), some commands will differ, mainly because it is not the same version of ROS, however as a whole, there should not be too much difference.

You will just have to clone the old repository and generate the Doxyfile.

By the way, don't hesitate to report other problems on this repository. For the moment, I didn't have the great opportunity to make real tests with real time robots.

Best regards.

**Comment by jn128c** [comment]
yes the doc from the original package is quite good. It took me only 10 hours or so to move the servo :-)
There is not much stuff out for pca9685 for ros (1/2) specialy for 2. So thanks for your work!

The servo was the last part to migrate to ros2 :-)

**Comment by vertueux** [comment]
Glad to hear this package worked for you!

As I said before, if you have modified some code or even added some, don't hesitate to make a pull request to share it with everyone 🙂.

I remember making several unsuccessful attempts to enable communication and servo rotation before.
